USE [master]
GO
/****** Object:  Database [Servicios]    Script Date: 9/24/2022 5:59:22 PM ******/
CREATE DATABASE [Servicios]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Servicios', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Servicios.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Servicios_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Servicios_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Servicios] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Servicios].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Servicios] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Servicios] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Servicios] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Servicios] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Servicios] SET ARITHABORT OFF 
GO
ALTER DATABASE [Servicios] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Servicios] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Servicios] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Servicios] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Servicios] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Servicios] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Servicios] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Servicios] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Servicios] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Servicios] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Servicios] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Servicios] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Servicios] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Servicios] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Servicios] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Servicios] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Servicios] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Servicios] SET RECOVERY FULL 
GO
ALTER DATABASE [Servicios] SET  MULTI_USER 
GO
ALTER DATABASE [Servicios] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Servicios] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Servicios] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Servicios] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Servicios] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Servicios] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Servicios', N'ON'
GO
ALTER DATABASE [Servicios] SET QUERY_STORE = OFF
GO
USE [Servicios]
GO
/****** Object:  Table [dbo].[Persona]    Script Date: 9/24/2022 5:59:23 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Persona](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[idTipoDocumentoIdentidad] [int] NOT NULL,
	[Nombre] [varchar](32) NOT NULL,
	[ValorDocumentoIdentidad] [varchar](32) NOT NULL,
 CONSTRAINT [PK_Persona] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TipoDocumentoIdentidad]    Script Date: 9/24/2022 5:59:23 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TipoDocumentoIdentidad](
	[id] [int] NOT NULL,
	[Nombre] [varchar](32) NOT NULL,
	[Mascara] [varchar](32) NOT NULL,
 CONSTRAINT [PK_TipoDocumentoIdentidad] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Persona]  WITH CHECK ADD  CONSTRAINT [FK_Persona_TipoDocumentoIdentidad] FOREIGN KEY([idTipoDocumentoIdentidad])
REFERENCES [dbo].[TipoDocumentoIdentidad] ([id])
GO
ALTER TABLE [dbo].[Persona] CHECK CONSTRAINT [FK_Persona_TipoDocumentoIdentidad]
GO
USE [master]
GO
ALTER DATABASE [Servicios] SET  READ_WRITE 
GO
